on:
  push:
    branches:
      - main

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.changes.outputs.backend }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for changes in backend
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            backend:
              - 'backed/**'

  backend:
    needs: check-changes
    runs-on: ubuntu-latest
    if: needs.check-changes.outputs.backend == 'true'

    steps:
      - name: Nice working
        run: echo "Changes detected in backed folder. Proceeding with backend job."
       
             
