name: Backend CI

on:
  push:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}

    steps:
      - uses: actions/checkout@v4

      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            backend:
              - 'backend/**'

  backend:
    needs: check
    if: needs.check.outputs.backend == 'true'
    runs-on: ubuntu-latest

    steps:
      - run: echo "🚀 Backend changes detected!"